spring:
  datasource:
    url: jdbc:mysql://192.168.17.1/taobao
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.17.128
    virtual-host: /
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.17.128:2181
  protocol:
    port: -1
    name: dubbo

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2-dev.xml