dubbo:
  application:
    name: search_service
  registry:
    address: zookeeper://192.168.17.128:2181
  protocol:
    port: -1
    name: dubbo

spring:
  data:
    solr:
      host: http://192.168.17.128:8983/solr/mycollection
  rabbitmq:
    host: 192.168.17.128
    virtual-host: /


